import AbstractPersonalPetManagementPageProcessor from "./AbstractPersonalPetManagementPageProcessor";

class PersonalPetManagementPageProcessor_Castle extends AbstractPersonalPetManagementPageProcessor {

}

export = PersonalPetManagementPageProcessor_Castle;